config/routes.rb
Rails.application.routes.draw do
  resources :factions
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get 'help' => 'static_pages#comingSoon' #get 'static_pages/help'
  get 'about' => 'static_pages#comingSoon' #get 'static_pages/help'
  get 'contact' => 'static_pages#contact' #get 'static_pages/help'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  get 'leaderboard' => 'static_pages#leaderboard'

end

app/models/faction.rb
class Faction < ActiveRecord::Base
    has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  belongs_to :faction
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/factions_controller.rb
class FactionsController < ApplicationController
  before_action :set_faction, only: [:show, :edit, :update, :destroy]

  # GET /factions
  # GET /factions.json
  def index
    @factions = Faction.all
  end

  # GET /factions/1
  # GET /factions/1.json
  def show
  end

  # GET /factions/new
  def new
    @faction = Faction.new
  end

  # GET /factions/1/edit
  def edit
  end

  # POST /factions
  # POST /factions.json
  def create
    @faction = Faction.new(faction_params)

    respond_to do |format|
      if @faction.save
        format.html { redirect_to @faction, notice: 'Faction was successfully created.' }
        format.json { render :show, status: :created, location: @faction }
      else
        format.html { render :new }
        format.json { render json: @faction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /factions/1
  # PATCH/PUT /factions/1.json
  def update
    respond_to do |format|
      if @faction.update(faction_params)
        format.html { redirect_to @faction, notice: 'Faction was successfully updated.' }
        format.json { render :show, status: :ok, location: @faction }
      else
        format.html { render :edit }
        format.json { render json: @faction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factions/1
  # DELETE /factions/1.json
  def destroy
    @faction.destroy
    respond_to do |format|
      format.html { redirect_to factions_url, notice: 'Faction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faction
      @faction = Faction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faction_params
      params.require(:faction).permit(:name, :numMembers, :currentGame, :admin)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end
  def destroy
    log_out
    flash[:info] = "You're logged out. See you soon."
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
  def comingSoon
  end
  
  def leaderboard
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
    @factions = Faction.all
  end
  
  def show
    @user = User.find(params[:id])
    @faction = Faction.find(@user.faction_id)
  end
  
  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      # Handle a successful save.
      log_in @user
      flash[:success] = "Welcome to GameWeek!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
    @factions = Faction.all
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :faction_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "GameWeek"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      page_title + " | " + base_title                 # String concatenation
    end
  end
end

app/helpers/factions_helper.rb
module FactionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/factions/_form.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-4">
<%= form_for(@faction) do |f| %>
  <% if @faction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faction.errors.count, "error") %> prohibited this faction from being saved:</h2>

      <ul>
      <% @faction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :"Number of Members" %><br>
    <%= f.number_field :numMembers %>
  </div>
  <div class="field">
    <%= f.label :"Current Game" %><br>
    <%= f.text_field :currentGame %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.text_field :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</div>

app/views/factions/edit.html.erb
<% provide(:title, @faction.name) %>

<h1>Editing Faction</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-4">
    <%= form_for(@faction) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :"Number of Members" %>
      <%= f.number_field :numMembers, class: 'form-control' %>
      
      <%= f.label :"Current Game" %><br />
      <%= f.text_field :currentGame, class: 'form-control'%><br />

      <%= f.label :Administrator %>
      <%= f.text_field :admin, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    
  </div>
</div>

app/views/factions/index.html.erb
<% provide(:title, "Factions") %>

<p id="notice"><%= notice %></p>

<div class='tableMain'id="factions-div">
      <div class='container'>
        <table class='tab'>
          <caption><h1><span>Listing Factions<span></h1><caption>
          <tr>
            <th>Faction</th>
            <th># Members</th>
            <th>Current Game</th>
            <th>Administrator</th>
            <th colspan='3'></th>
          </tr>
          <% @factions.each do |faction| %>
          <tr>
            <td class="first-faction"><%= faction.name %></td>
            <td><%= faction.numMembers %></td>
            <td><%= faction.currentGame %></td>
            <td><%= faction.admin %></td>
            <td><%= link_to 'Show', faction %></td>
          </tr>
          <% end %>
        </table>
      </div> <!-- c -->
    </div> <!-- main -->

<br>

<%= link_to 'New Faction', new_faction_path %>

app/views/factions/new.html.erb
<h1>New Faction</h1>

<%= render 'form' %>

<%= link_to 'Back', factions_path %>

app/views/factions/show.html.erb
<% provide(:title, @faction.name) %>

<div class="row">
  <div class="col-md-6 col-md-offset-4">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @faction.name %>
</p>

<p>
  <strong>Nummembers:</strong>
  <%= @faction.numMembers %>
</p>

<p>
  <strong>Currentgame:</strong>
  <%= @faction.currentGame %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @faction.admin %>
</p>

<%= link_to 'Edit', edit_faction_path(@faction) %> |
<%= link_to 'Back', factions_path %>

</div></div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    By <a target="_blank" href="http://www.kevinivey.com/">Kevin Ivey</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a target="_blank" href="http://www.reddit.com/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Game Week", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path, id: "topLink" %></li>
            <li><%= link_to "Help",   help_path, id: "topLink" %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", users_path, id: "topLink" %></li>
              <li><%= link_to "Factions", factions_path, id: "topLink" %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" id="topLink" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user, id: "dropdownmenu" %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user), id: "dropdownmenu" %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete", id: "dropdownmenu" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path, id: "topLink" %></li>
            <% end %>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if !Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/comingSoon.html.erb
<% provide(:title, 'Coming Soon') %>
<h1>Coming Soon</h1>
<p>This page is currently under construction. Check back soon!</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact <a href="http://www.kevinivey.com" target="_blank">the guy</a> who made this.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>GameWeek on Rails</h1>

  <h2>
    Home page for the new
    <a target="_blank" href="https://php.radford.edu/~kivey/GameWeek/">GameWeek</a>
    application built on Rails.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary", id: "main-btn"%>
</div>

app/views/static_pages/leaderboard.html.erb
<% provide(:title, "Leaderboard") %>

<p id="notice"><%= notice %></p>

<div class='tableMain'id="factions-div">
      <div class='container'>
        <table class='tab'>
          <caption><h1><span>Leaderboard<span></h1><caption>
          <tr>
            <th>Username</th>
            <th># Wins</th>
            <th>All-Time Wins</th>
            <th># Weeks Won</th>
            <th colspan='3'></th>
          </tr>
          <tr>
            <td class="first-faction">current-user</td>
            <td>3</td>
            <td>9</td>
            <td>1</td>
            <td></td>
          </tr>
        </table>
      </div> <!-- c -->
    </div> <!-- main -->

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-4">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :faction %><br />
      <%= f.collection_select :faction_id, @factions, :id, :name, class: 'form-control'%><br />

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'GameWeek Users') %>
<h1>GameWeek Users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-4">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.label :faction %><br />
      <%= f.collection_select :faction_id, @factions, :id, :name, class: 'form-control'%><br />

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="container-fluid" id="profile-div">
<h1>Profile page for <%=  @user.name %></h1>


  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <section class="user_info">
          <h3>User: <%= @user.name %></h3>
          <h3>Faction: <%= @faction.name %></h3>
          <h3>Current Game: <%= @faction.currentGame %></h3>
          <h3 id="displayName">
            <%= gravatar_for @user %>
          </h3>
        </section>
      </div>
      <div class="col-md-4 col-md-offset-2">
        <h3><a href="/leaderboard">Leaderboard</a></h3>
        <h3><a href="#">Wins</a></h3>
        <h3><a href="#">Weekly Vote</a></h3>
      </div>
    </div>
  </div>
</div>